#!/bin/sh
set -e
shift

OUTDIR=$(mktemp -d)

function cleanup {
    rm -rf $OUTDIR
}

trap cleanup EXIT

$DEBUG cargo build -Z unstable-options --out-dir "$OUTDIR" "$@"

for MOD in "$OUTDIR"/*.so; do
    ARCH="$(readelf -h "$MOD" | grep Machine | tr -s ' ' | cut '-d ' -f3-)"
    if [[ "$ARCH" == "ARM" ]]; then
        $DEBUG adb push "$OUTDIR"/*.so "/sdcard/Android/data/com.beatgames.beatsaber/files/mods/"
    fi
done

$DEBUG adb shell am force-stop com.beatgames.beatsaber
$DEBUG adb shell am start com.beatgames.beatsaber/com.unity3d.player.UnityPlayerActivity
